/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Event" CASCADE;

CREATE TABLE "Event" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "type" SMALLINT NOT NULL,
  "description" VARCHAR(128) NOT NULL,
  "location" VARCHAR(128) NOT NULL);

