/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "event" CASCADE;

CREATE TABLE "event" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "type" SMALLINT NOT NULL,
  "item" BIGINT NULL,
  "description" VARCHAR(128) NOT NULL,
  "location" VARCHAR(128) NOT NULL);

ALTER TABLE "event"
  ADD CONSTRAINT "item_fk"
    FOREIGN KEY ("item")
    REFERENCES "timelineitem" ("id")
    INITIALLY DEFERRED;

