// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "TimelineItem-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // TimelineItem
  //

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::
  persist_statement_name[] = "persist_timelineitem";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::
  find_statement_name[] = "find_timelineitem";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::
  update_statement_name[] = "update_timelineitem";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::
  erase_statement_name[] = "erase_timelineitem";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::
  query_statement_name[] = "query_timelineitem";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::
  erase_query_statement_name[] = "erase_query_timelineitem";

  const unsigned int access::object_traits_impl< ::TimelineItem, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::TimelineItem, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::TimelineItem, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  const char alias_traits<  ::Event,
    id_pgsql,
    access::object_traits_impl< ::TimelineItem, id_pgsql >::event_tag>::
  table_name[] = "\"event\"";

  const char alias_traits<  ::TimelineItem,
    id_pgsql,
    access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_tag>::
  table_name[] = "\"linked\"";

  struct access::object_traits_impl< ::TimelineItem, id_pgsql >::extra_statement_cache_type
  {
    pgsql::container_statements_impl< linked_items_traits > linked_items_;

    extra_statement_cache_type (
      pgsql::connection& c,
      image_type&,
      id_image_type&,
      pgsql::binding& id,
      pgsql::binding&,
      pgsql::native_binding& idn,
      const unsigned int* idt)
    : linked_items_ (c, id, idn, idt)
    {
    }
  };

  // linked_items_
  //

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  select_name[] = "select_timelineitem_linked_items";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  insert_name[] = "insert_timelineitem_linked_items";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  delete_name[] = "delete_timelineitem_linked_items";

  const unsigned int access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  insert_types[] =
  {
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid
  };

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  select_statement[] =
  "SELECT "
  "\"timelineitem_linked_items\".\"index\", "
  "\"timelineitem_linked_items\".\"value\" "
  "FROM \"timelineitem_linked_items\" "
  "WHERE \"timelineitem_linked_items\".\"object_id\"=$1 ORDER BY \"timelineitem_linked_items\".\"index\"";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  insert_statement[] =
  "INSERT INTO \"timelineitem_linked_items\" "
  "(\"object_id\", "
  "\"index\", "
  "\"value\") "
  "VALUES "
  "($1, $2, $3)";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  delete_statement[] =
  "DELETE FROM \"timelineitem_linked_items\" "
  "WHERE \"object_id\"=$1";

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  bind (pgsql::bind* b,
        const pgsql::bind* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace pgsql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  grow (data_image_type& i,
        bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace pgsql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      pgsql::value_traits<
          index_type,
          pgsql::id_bigint >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::TimelineItem > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        throw null_pointer ();
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      pgsql::value_traits<
          index_type,
          pgsql::id_bigint >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::TimelineItem > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<pgsql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace pgsql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace pgsql;
    using pgsql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  delete_ (void* d)
  {
    using namespace pgsql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace pgsql;
    using pgsql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::linked_items_traits::
  erase (statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  access::object_traits_impl< ::TimelineItem, id_pgsql >::id_type
  access::object_traits_impl< ::TimelineItem, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::TimelineItem, id_pgsql >::id_type
  access::object_traits_impl< ::TimelineItem, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::TimelineItem, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // event_
    //
    t[1UL] = 0;

    // start_
    //
    t[2UL] = 0;

    // end_
    //
    t[3UL] = 0;

    // linked_
    //
    t[4UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // event_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.event_value;
    b[n].is_null = &i.event_null;
    n++;

    // start_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.start_value;
    b[n].is_null = &i.start_null;
    n++;

    // end_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.end_value;
    b[n].is_null = &i.end_null;
    n++;

    // linked_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.linked_value;
    b[n].is_null = &i.linked_null;
    n++;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::TimelineItem, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // event_
    //
    {
      ::std::shared_ptr< ::Event > const& v =
        o.event_;

      typedef object_traits< ::Event > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::Event > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i.event_value, is_null, id);
        i.event_null = is_null;
      }
      else
        throw null_pointer ();
    }

    // start_
    //
    {
      ::time_t const& v =
        o.start_;

      bool is_null (false);
      pgsql::value_traits<
          ::time_t,
          pgsql::id_bigint >::set_image (
        i.start_value, is_null, v);
      i.start_null = is_null;
    }

    // end_
    //
    {
      ::time_t const& v =
        o.end_;

      bool is_null (false);
      pgsql::value_traits<
          ::time_t,
          pgsql::id_bigint >::set_image (
        i.end_value, is_null, v);
      i.end_null = is_null;
    }

    // linked_
    //
    {
      ::std::shared_ptr< ::TimelineItem > const& v =
        o.linked_;

      typedef object_traits< ::TimelineItem > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::TimelineItem > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i.linked_value, is_null, id);
        i.linked_null = is_null;
      }
      else
        i.linked_null = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long unsigned int& v =
        o.id_;

      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // event_
    //
    {
      ::std::shared_ptr< ::Event >& v =
        o.event_;

      typedef object_traits< ::Event > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::Event > > ptr_traits;

      if (i.event_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          id,
          i.event_value,
          i.event_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<pgsql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }

    // start_
    //
    {
      ::time_t& v =
        o.start_;

      pgsql::value_traits<
          ::time_t,
          pgsql::id_bigint >::set_value (
        v,
        i.start_value,
        i.start_null);
    }

    // end_
    //
    {
      ::time_t& v =
        o.end_;

      pgsql::value_traits<
          ::time_t,
          pgsql::id_bigint >::set_value (
        v,
        i.end_value,
        i.end_null);
    }

    // linked_
    //
    {
      ::std::shared_ptr< ::TimelineItem >& v =
        o.linked_;

      typedef object_traits< ::TimelineItem > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::TimelineItem > > ptr_traits;

      if (i.linked_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          id,
          i.linked_value,
          i.linked_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<pgsql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long unsigned int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::persist_statement[] =
  "INSERT INTO \"timelineitem\" "
  "(\"id\", "
  "\"event\", "
  "\"start\", "
  "\"end\", "
  "\"linked\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::find_statement[] =
  "SELECT "
  "\"timelineitem\".\"id\", "
  "\"timelineitem\".\"event\", "
  "\"timelineitem\".\"start\", "
  "\"timelineitem\".\"end\", "
  "\"timelineitem\".\"linked\" "
  "FROM \"timelineitem\" "
  "WHERE \"timelineitem\".\"id\"=$1";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::update_statement[] =
  "UPDATE \"timelineitem\" "
  "SET "
  "\"event\"=$1, "
  "\"start\"=$2, "
  "\"end\"=$3, "
  "\"linked\"=$4 "
  "WHERE \"id\"=$5";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::erase_statement[] =
  "DELETE FROM \"timelineitem\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::query_statement[] =
  "SELECT\n"
  "\"timelineitem\".\"id\",\n"
  "\"timelineitem\".\"event\",\n"
  "\"timelineitem\".\"start\",\n"
  "\"timelineitem\".\"end\",\n"
  "\"timelineitem\".\"linked\"\n"
  "FROM \"timelineitem\"\n"
  "LEFT JOIN \"event\" AS \"event\" ON \"event\".\"id\"=\"timelineitem\".\"event\"\n"
  "LEFT JOIN \"timelineitem\" AS \"linked\" ON \"linked\".\"id\"=\"timelineitem\".\"linked\"";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"timelineitem\"";

  const char access::object_traits_impl< ::TimelineItem, id_pgsql >::table_name[] =
  "\"timelineitem\"";

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    id_image_type& i (sts.id_image ());
    init (i, obj.id_);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // linked_items_
    //
    {
      ::std::vector< ::std::shared_ptr< ::TimelineItem > > const& v =
        obj.linked_items_;

      linked_items_traits::persist (
        v,
        esc.linked_items_);
    }

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // linked_items_
    //
    {
      ::std::vector< ::std::shared_ptr< ::TimelineItem > > const& v =
        obj.linked_items_;

      linked_items_traits::update (
        v,
        esc.linked_items_);
    }

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // linked_items_
    //
    linked_items_traits::erase (
      esc.linked_items_);

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TimelineItem, id_pgsql >::pointer_type
  access::object_traits_impl< ::TimelineItem, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TimelineItem, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TimelineItem, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TimelineItem, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TimelineItem, id_pgsql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // linked_items_
    //
    {
      ::std::vector< ::std::shared_ptr< ::TimelineItem > >& v =
        obj.linked_items_;

      linked_items_traits::load (
        v,
        esc.linked_items_);
    }
  }

  result< access::object_traits_impl< ::TimelineItem, id_pgsql >::object_type >
  access::object_traits_impl< ::TimelineItem, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        true,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TimelineItem, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
