/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "TimelineItem_linked_items" CASCADE;

DROP TABLE IF EXISTS "TimelineItem" CASCADE;

CREATE TABLE "TimelineItem" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "event" BIGINT NULL,
  "start" BIGINT NOT NULL,
  "end" BIGINT NOT NULL,
  "linked" BIGINT NULL,
  CONSTRAINT "linked_fk"
    FOREIGN KEY ("linked")
    REFERENCES "TimelineItem" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "TimelineItem_linked_items" (
  "object_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "value" BIGINT NULL,
  CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "TimelineItem" ("id")
    ON DELETE CASCADE,
  CONSTRAINT "value_fk"
    FOREIGN KEY ("value")
    REFERENCES "TimelineItem" ("id")
    INITIALLY DEFERRED);

CREATE INDEX "TimelineItem_linked_items_object_id_i"
  ON "TimelineItem_linked_items" ("object_id");

CREATE INDEX "TimelineItem_linked_items_index_i"
  ON "TimelineItem_linked_items" ("index");

ALTER TABLE "TimelineItem"
  ADD CONSTRAINT "event_fk"
    FOREIGN KEY ("event")
    REFERENCES "Event" ("id")
    INITIALLY DEFERRED;

