/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Timeline_timeline_items" CASCADE;

DROP TABLE IF EXISTS "Timeline" CASCADE;

CREATE TABLE "Timeline" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "event_colour" VARCHAR(128) NOT NULL,
  "meeting_colour" VARCHAR(128) NOT NULL,
  "assignment_colour" VARCHAR(128) NOT NULL);

CREATE TABLE "Timeline_timeline_items" (
  "object_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "value" INTEGER NOT NULL,
  CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "Timeline" ("id")
    ON DELETE CASCADE);

CREATE INDEX "Timeline_timeline_items_object_id_i"
  ON "Timeline_timeline_items" ("object_id");

CREATE INDEX "Timeline_timeline_items_index_i"
  ON "Timeline_timeline_items" ("index");

