// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TIMELINE_ODB_HXX
#define TIMELINE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Timeline.hpp"

#include "Event-odb.hxx"
#include "TimelineItem-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Timeline
  //
  template <>
  struct class_traits< ::Timeline >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Timeline >
  {
    public:
    typedef ::Timeline object_type;
    typedef ::Timeline* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // Timeline
  //
  template <typename A>
  struct query_columns< ::Timeline, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // colour_one
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    colour_one_type_;

    static const colour_one_type_ colour_one;

    // colour_two
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    colour_two_type_;

    static const colour_two_type_ colour_two;

    // colour_three
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    colour_three_type_;

    static const colour_three_type_ colour_three;

    // label_one
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    label_one_type_;

    static const label_one_type_ label_one;

    // label_two
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    label_two_type_;

    static const label_two_type_ label_two;

    // label_three
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    label_three_type_;

    static const label_three_type_ label_three;
  };

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::id_type_
  query_columns< ::Timeline, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::colour_one_type_
  query_columns< ::Timeline, id_pgsql, A >::
  colour_one (A::table_name, "\"colour_one\"", 0);

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::colour_two_type_
  query_columns< ::Timeline, id_pgsql, A >::
  colour_two (A::table_name, "\"colour_two\"", 0);

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::colour_three_type_
  query_columns< ::Timeline, id_pgsql, A >::
  colour_three (A::table_name, "\"colour_three\"", 0);

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::label_one_type_
  query_columns< ::Timeline, id_pgsql, A >::
  label_one (A::table_name, "\"label_one\"", 0);

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::label_two_type_
  query_columns< ::Timeline, id_pgsql, A >::
  label_two (A::table_name, "\"label_two\"", 0);

  template <typename A>
  const typename query_columns< ::Timeline, id_pgsql, A >::label_three_type_
  query_columns< ::Timeline, id_pgsql, A >::
  label_three (A::table_name, "\"label_three\"", 0);

  template <typename A>
  struct pointer_query_columns< ::Timeline, id_pgsql, A >:
    query_columns< ::Timeline, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Timeline, id_pgsql >:
    public access::object_traits< ::Timeline >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // colour_one_
      //
      details::buffer colour_one_value;
      std::size_t colour_one_size;
      bool colour_one_null;

      // colour_two_
      //
      details::buffer colour_two_value;
      std::size_t colour_two_size;
      bool colour_two_null;

      // colour_three_
      //
      details::buffer colour_three_value;
      std::size_t colour_three_size;
      bool colour_three_null;

      // label_one_
      //
      details::buffer label_one_value;
      std::size_t label_one_size;
      bool label_one_null;

      // label_two_
      //
      details::buffer label_two_value;
      std::size_t label_two_size;
      bool label_two_null;

      // label_three_
      //
      details::buffer label_three_value;
      std::size_t label_three_size;
      bool label_three_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // timeline_items_
    //
    struct timeline_items_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::std::shared_ptr< ::TimelineItem > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< timeline_items_traits > statements_type;

      struct data_image_type
      {
        // index
        //
        long long index_value;
        bool index_null;

        // value
        //
        long long value_value;
        bool value_null;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (data_image_type&,
            index_type*,
            const value_type&);

      static void
      init (index_type&,
            value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      persist (const container_type&,
               statements_type&);

      static void
      load (container_type&,
            statements_type&);

      static void
      update (const container_type&,
              statements_type&);

      static void
      erase (statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Timeline, id_common >:
    public access::object_traits_impl< ::Timeline, id_pgsql >
  {
  };

  // Timeline
  //
}

#include "Timeline-odb.ixx"

#include <odb/post.hxx>

#endif // TIMELINE_ODB_HXX
