/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(128) NOT NULL,
  "email" VARCHAR(128) NOT NULL,
  "password" VARCHAR(128) NOT NULL,
  "timeline" BIGINT NULL,
  "create_date" BIGINT NOT NULL,
  "activated" SMALLINT NOT NULL,
  "last_ip" VARCHAR(128) NOT NULL,
  "ones" INTEGER NOT NULL,
  "twos" INTEGER NOT NULL,
  "threes" INTEGER NOT NULL,
  "client_key" VARCHAR(128) NOT NULL);

ALTER TABLE "user"
  ADD CONSTRAINT "timeline_fk"
    FOREIGN KEY ("timeline")
    REFERENCES "timeline" ("id")
    INITIALLY DEFERRED;

