# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_one', models.CharField(default='red', max_length=10)),
                ('colour_two', models.CharField(default='green', max_length=10)),
                ('colour_three', models.CharField(default='blue', max_length=10)),
                ('label_one', models.CharField(default='Meeting', max_length=15)),
                ('label_two', models.CharField(default='Assignment', max_length=15)),
                ('label_three', models.CharField(default='Event', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octagon.Timeline')),
            ],
        ),
    ]
