# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octagon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='location',
            field=models.CharField(default='heyyea', max_length=255),
            preserve_default=False,
        ),
    ]
